#!/usr/bin/env python3
"""
© NAuliajati - TangerangKota-CSIRT
GENERATED FILE - do not edit. Produced by bake_mitre_tactics.py.

Source      : /var/log/blue-team-mcp/mitre_enterprise_attack.json
Source sha256: 7a98924cfb2c0fb7688c6b7ed6b2dfc126c189caced3ce9f771ec82675204e22
ATT&CK      : 19.2
Tactics     : 15 x-mitre-tactic objects
Generated   : 2026-09-24T05:55:27Z

Runtime imports this module instead of parsing the STIX bundle, so the labeler
does no I/O and no network. Regenerate after an ATT&CK release, or when
constants.MITRE_TACTIC_TO_CATEGORY gains a tactic:
    python3 bake_mitre_tactics.py --bundle /var/log/blue-team-mcp/mitre_enterprise_attack.json

Descriptions are provenance for humans; the classifier prompt lives in
criteria.py, which keeps its own one-line phrases per tactic.
"""
SOURCE = "/var/log/blue-team-mcp/mitre_enterprise_attack.json"
SOURCE_SHA256 = "7a98924cfb2c0fb7688c6b7ed6b2dfc126c189caced3ce9f771ec82675204e22"
ATTACK_VERSION = "19.2"

TACTICS: dict[str, dict[str, str]] = {
    "initial-access": {"name": "Initial Access", "external_id": "TA0001", "description": "The adversary is trying to get into your network. Initial Access consists of techniques that use various entry vectors to gain their initial foothold within a network. Techniques used to gain a foothold include targeted spearphishing and exploiting weaknesses on public-facing web servers. Footholds gained through initial access may allow for continued access, like valid accounts and use of external remote services, or may be limited-use due to changing passwords."},
    "execution": {"name": "Execution", "external_id": "TA0002", "description": "The adversary is trying to run malicious code. Execution consists of techniques that result in adversary-controlled code running on a local or remote system. Techniques that run malicious code are often paired with techniques from all other tactics to achieve broader goals, like exploring a network or stealing data. For example, an adversary might use a remote access tool to run a PowerShell script that does Remote System Discovery."},
    "persistence": {"name": "Persistence", "external_id": "TA0003", "description": "The adversary is trying to maintain their foothold. Persistence consists of techniques that adversaries use to keep access to systems across restarts, changed credentials, and other interruptions that could cut off their access. Techniques used for persistence include any access, action, or configuration changes that let them maintain their foothold on systems, such as replacing or hijacking legitimate code or adding startup code."},
    "privilege-escalation": {"name": "Privilege Escalation", "external_id": "TA0004", "description": "The adversary is trying to gain higher-level permissions. Privilege Escalation consists of techniques that adversaries use to gain higher-level permissions on a system or network. Adversaries can often enter and explore a network with unprivileged access but require elevated permissions to follow through on their objectives. Common approaches are to take advantage of system weaknesses, misconfigurations, and vulnerabilities. Examples of elevated access include: * SYSTEM/root level * local administrator * user account with admin-like access * user accounts with access to specific system or perform specific function These techniques often overlap with Persistence techniques, as OS features that let an adversary persist can execute in an elevated context."},
    "stealth": {"name": "Stealth", "external_id": "TA0005", "description": "The adversary is trying to hide and conceal their actions, appearing as normal behavior. Stealth consists of techniques that reduce the likelihood of detection by blending in with legitimate activity or minimizing observable signals. These techniques are characterized by concealment behaviors, such as avoiding, obfuscating, or mimicking normal operations, without modifying security controls or compromising collection and monitoring feeds. The goal is to remain indistinguishable from benign activity while leaving defensive systems intact."},
    "credential-access": {"name": "Credential Access", "external_id": "TA0006", "description": "The adversary is trying to steal account names and passwords. Credential Access consists of techniques for stealing credentials like account names and passwords. Techniques used to get credentials include keylogging or credential dumping. Using legitimate credentials can give adversaries access to systems, make them harder to detect, and provide the opportunity to create more accounts to help achieve their goals."},
    "discovery": {"name": "Discovery", "external_id": "TA0007", "description": "The adversary is trying to figure out your environment. Discovery consists of techniques an adversary may use to gain knowledge about the system and internal network. These techniques help adversaries observe the environment and orient themselves before deciding how to act. They also allow adversaries to explore what they can control and what\u2019s around their entry point in order to discover how it could benefit their current objective. Native operating system tools are often used toward this post-compromise information-gathering objective."},
    "lateral-movement": {"name": "Lateral Movement", "external_id": "TA0008", "description": "The adversary is trying to move through your environment. Lateral Movement consists of techniques that adversaries use to enter and control remote systems on a network. Following through on their primary objective often requires exploring the network to find their target, then pivoting through multiple systems and accounts to gain access to it. Adversaries might install their own remote access tools to accomplish Lateral Movement or use legitimate credentials with native network and operating system tools, which may be stealthier."},
    "collection": {"name": "Collection", "external_id": "TA0009", "description": "The adversary is trying to gather data of interest to their goal. Collection consists of techniques adversaries may use to gather information and the sources information is collected from that are relevant to following through on the adversary's objectives. Frequently, the next goal after collecting data is to either steal (exfiltrate) the data or to use the data to gain more information about the target environment. Common target sources include various drive types, browsers, audio, video, and email. Common collection methods include capturing screenshots and keyboard input."},
    "exfiltration": {"name": "Exfiltration", "external_id": "TA0010", "description": "The adversary is trying to steal data. Exfiltration consists of techniques that adversaries may use to steal data from your network. Once they\u2019ve collected data, adversaries often package it to avoid detection while removing it. This can include compression and encryption. Techniques for getting data out of a target network typically include transferring it over their command and control channel or an alternate channel and may also include putting size limits on the transmission."},
    "command-and-control": {"name": "Command and Control", "external_id": "TA0011", "description": "The adversary is trying to communicate with compromised systems to control them. Command and Control consists of techniques that adversaries may use to communicate with systems under their control within a victim network. Adversaries commonly attempt to mimic normal, expected traffic to avoid detection. There are many ways an adversary can establish command and control with various levels of stealth depending on the victim\u2019s network structure and defenses."},
    "impact": {"name": "Impact", "external_id": "TA0040", "description": "The adversary is trying to manipulate, interrupt, or destroy your systems and data. Impact consists of techniques that adversaries use to disrupt availability or compromise integrity by manipulating business and operational processes. Techniques used for impact can include destroying or tampering with data. In some cases, business processes can look fine, but may have been altered to benefit the adversaries\u2019 goals. These techniques might be used by adversaries to follow through on their end goal or to provide cover for a confidentiality breach."},
    "resource-development": {"name": "Resource Development", "external_id": "TA0042", "description": "The adversary is trying to establish resources they can use to support operations. Resource Development consists of techniques that involve adversaries creating, purchasing, or compromising/stealing resources that can be used to support targeting. Such resources include infrastructure, accounts, or capabilities. These resources can be leveraged by the adversary to aid in other phases of the adversary lifecycle, such as using purchased domains to support Command and Control, email accounts for phishing as a part of Initial Access, or stealing code signing certificates to help with Defense Evasion."},
    "reconnaissance": {"name": "Reconnaissance", "external_id": "TA0043", "description": "The adversary is trying to gather information they can use to plan future operations. Reconnaissance consists of techniques that involve adversaries actively or passively gathering information that can be used to support targeting. Such information may include details of the victim organization, infrastructure, or staff/personnel. This information can be leveraged by the adversary to aid in other phases of the adversary lifecycle, such as using gathered information to plan and execute Initial Access, to scope and prioritize post-compromise objectives, or to drive and lead further Reconnaissance efforts."},
    "defense-impairment": {"name": "Defense Impairment", "external_id": "TA0112", "description": "The adversary is trying to break security mechanisms, pipelines, and tooling so defenders can\u2019t see or trust what\u2019s happening. Defense Impairment consists of techniques that degrade, disable, or undermine the effectiveness and trustworthiness of security controls and monitoring mechanisms. These techniques are characterized by direct interference with defensive systems. The goal is to reduce defenders\u2019 ability to detect, interpret, or respond to adversary activity."},
}
